name: Building and deploying Github-Pages MKDocs generated documentation.
description: Deploying new documentation to GitHub Pages.

inputs:
  PYTHON_VERSION:
    description: "Python version to use for this action. Default is 3.9"
    required: false
    default: 3.11

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "${{ inputs.PYTHON_VERSION }}"
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # installing poetry
        pip install poetry
        # assuring we have all extras for testing as well
        poetry install --all-extras --no-interaction
      shell: bash
    - name: Build and Deploy the Doc
      shell: bash
      run: |
        mkdocs gh-deploy --config-file mkdocs.yml --force
        echo "DOC GENERATED - OK!"
