name: Docs Build and Deploy

on:
  push:
    branches: [main, dev]
    paths: ["docs/**", "mkdocs.yml", "pyproject.toml"]
  pull_request:
    branches: [main, dev]
    paths: ["docs/**", "mkdocs.yml", "pyproject.toml"]
  workflow_dispatch:

jobs:
  setup:
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    uses: ./.github/workflows/reusable-python-setup.yml
    with:
      python-version: ${{ matrix.python-version }}

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
      - name: Install dependencies
        run: poetry install --with dev --no-interaction
      - name: Check mkdocs install
        run: poetry run mkdocs --version
      - name: Build docs
        run: poetry run mkdocs build
      - name: Upload built docs
        uses: actions/upload-artifact@v4
        with:
          name: site-${{ matrix.python-version }}
          path: site/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
      - name: Install dependencies
        run: poetry install --with dev --no-interaction
      - name: Download built docs
        uses: actions/download-artifact@v4
        with:
          name: site-3.11
          path: site/
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Deploy docs with mike
        run: poetry run mike deploy --push --update-aliases $(poetry version -s) latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
