name: Manual Documentation Publish

on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        required: true
        type: string
        description: "Release version for documentation"
      UPDATE_LATEST:
        required: true
        type: boolean
        default: true
        description: "Update the 'latest' alias to point to this version"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
      - name: Cache Poetry and venv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install dependencies
        run: poetry install --with dev --no-interaction
      - name: Build docs
        run: poetry run mkdocs build
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Deploy documentation with mike
        run: |
          if [ "${{ inputs.UPDATE_LATEST }}" = "true" ]; then
            poetry run mike deploy --push --update-aliases ${{ inputs.RELEASE_VERSION }} latest
          else
            poetry run mike deploy --push ${{ inputs.RELEASE_VERSION }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
