name: Deploy PR Pages Preview

on:
  push:
    branches: [main, dev]
    paths: ["docs/**", "mkdocs.yml", "pyproject.toml"]
  pull_request:
    branches: [main, dev]
    paths: ["docs/**", "mkdocs.yml", "pyproject.toml"]
    types: [opened, reopened, edited, synchronize]
  workflow_dispatch:

concurrency:
  group: "preview-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  deploy-pr-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
      - name: Cache Poetry and venv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install dependencies
        run: poetry install --only doc --no-interaction
      - name: Build docs
        run: poetry run mkdocs build
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site/
          token: ${{ secrets.GITHUB_TOKEN }}
